# Generated by Django 4.2.7 on 2025-09-30 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.batch",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="farmer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "farmer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="users.location",
            ),
        ),
        migrations.AddIndex(
            model_name="verification",
            index=models.Index(
                fields=["product", "-verified_at"],
                name="products_ve_product_09dfe5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verification",
            index=models.Index(
                fields=["user", "-verified_at"], name="products_ve_user_id_71ec2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verification",
            index=models.Index(fields=["result"], name="products_ve_result_d5f2ba_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["qr_code"], name="products_pr_qr_code_fde6b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["creator", "-created_at"], name="products_pr_creator_7a3478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["biofortified", "status"], name="products_pr_biofort_72a76f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["product", "-issue_date"], name="products_ce_product_61fb1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["cert_type", "verified"], name="products_ce_cert_ty_be0e93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["farmer", "-created_at"], name="products_ba_farmer__036356_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["batch_number"], name="products_ba_batch_n_1e59ad_idx"
            ),
        ),
    ]
