# Generated by Django 4.2.7 on 2025-09-30 22:37

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amount (RWF)",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit", "Credit"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transaction Reference"
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplyChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(verbose_name="Step Number"),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("farmer", "Farmer"),
                            ("trader", "Trader"),
                            ("processor", "Processor"),
                            ("retailer", "Retailer"),
                            ("consumer", "Consumer"),
                        ],
                        max_length=20,
                        verbose_name="Actor Type",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("planted", "Planted"),
                            ("harvested", "Harvested"),
                            ("collected", "Collected"),
                            ("transported", "Transported"),
                            ("processed", "Processed"),
                            ("packaged", "Packaged"),
                            ("distributed", "Distributed"),
                            ("sold", "Sold"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "blockchain_hash",
                    models.CharField(
                        blank=True, max_length=66, verbose_name="Blockchain Hash"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Temperature (°C)",
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Humidity (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply Chain Step",
                "verbose_name_plural": "Supply Chain Steps",
                "ordering": ["product", "step_number"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantity (kg)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price (RWF)",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("harvest", "Harvest"),
                            ("transfer", "Transfer"),
                            ("processing", "Processing"),
                            ("sale", "Sale"),
                            ("return", "Return"),
                        ],
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "blockchain_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=66,
                        verbose_name="Blockchain Hash",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "transport_method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transport Method"
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Estimated Delivery"
                    ),
                ),
                (
                    "actual_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual Delivery"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
