# Generated by Django 4.2.7 on 2025-09-30 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_initial"),
        ("users", "0001_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="From User",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="users.location",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="To User",
            ),
        ),
        migrations.AddField(
            model_name="supplychain",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supply_chain_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplychain",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supply_chain_steps",
                to="users.location",
            ),
        ),
        migrations.AddField(
            model_name="supplychain",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supply_chain_steps",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="transactions.transaction",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["from_user", "-timestamp"],
                name="transaction_from_us_8aed5b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["to_user", "-timestamp"], name="transaction_to_user_383b64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["product", "-timestamp"], name="transaction_product_e3760a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "-timestamp"], name="transaction_status_8bdda2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["blockchain_hash"], name="transaction_blockch_fe484a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplychain",
            index=models.Index(
                fields=["product", "step_number"], name="transaction_product_fedf51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplychain",
            index=models.Index(
                fields=["actor", "-timestamp"], name="transaction_actor_i_8a12ea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplychain",
            unique_together={("product", "step_number")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-initiated_at"], name="transaction_status_71c5b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_reference"], name="transaction_transac_de6150_idx"
            ),
        ),
    ]
